extends Node

class_name Constants

enum JOB { COOK, COOK2, SERVER, DISHWASHER, GROCER, UNASSIGNED }
enum VICE { SMOKING, DRINKING, DRUGGING, FUCKING, CHILLING }
enum PERSONALITY { CHILL, BURNOUT, BULLY, SIDEKICK, ORGANIZER, SOCIALITE,THUG, PARTIER }
enum JOB_STATE { PROCEEDING_TO_WORK, WORKING, PROCEEDING_TO_VICE, VICING, IDLE }
