extends Node

class_name RatConstants

#region default values
const TRAIT_DEVIATION: Dictionary[TRAIT, float] = { 
	TRAIT.GREED: 35,
	TRAIT.TEMPER: 40,
	TRAIT.SOCIALNESS: 30,
	TRAIT.AMBITION: 45,
	TRAIT.LAZINESS: 50 
}
const TRAIT_MEAN: Dictionary[TRAIT, float] = {
	TRAIT.GREED: 40,
	TRAIT.TEMPER: 10,
	TRAIT.SOCIALNESS: 60,
	TRAIT.AMBITION: -20,
	TRAIT.LAZINESS: 20
}
const DEFAULT_MOOD: Dictionary[MOOD, float] = {
	MOOD.NUTRITION: 0,
	MOOD.ENERGY: 0,
	MOOD.STIMULATION: 0,
	MOOD.SOCIAL: 0,
	MOOD.VICE_SATISFACTION: 0,
}
const DEFAULT_STATUSES: Dictionary[STATUS, float] = {
	STATUS.STRESS: 0,
	STATUS.HEALTH: 100,
	STATUS.INEBRIATION: 0,
	STATUS.RADICALIZATION: 0,
	STATUS.EXTRA_STRESS: 0,
}
const DEFAULT_JOB_SKILLS: Dictionary[JobConstants.JOB, float] = {
	JobConstants.JOB.HEAD_COOK: 0,
	JobConstants.JOB.LINE_COOK: 0,
	JobConstants.JOB.PREP_COOK: 0,
	JobConstants.JOB.DISHWASHER: 0,
	JobConstants.JOB.BARTENDER: 0,
}
  

#endregion

#region mental statuses
enum VICE { SMOKING, DRINKING, DRUGGING, FUCKING, CHILLING }
enum PERSONALITY { CHILL, BURNOUT, BULLY, SIDEKICK, ORGANIZER, SOCIALITE,THUG, PARTIER }
enum TRAIT { GREED, TEMPER, SOCIALNESS, AMBITION, LAZINESS }
enum MOOD { NUTRITION, ENERGY, STIMULATION, SOCIAL, VICE_SATISFACTION }
#endregion

enum STATUS { STRESS, HEALTH, INEBRIATION, RADICALIZATION, EXTRA_STRESS}
enum JOB_STATE { PROCEEDING_TO_WORK, WORKING, PROCEEDING_TO_VICE, VICING, IDLE }
