extends Node

class_name RatConstants

enum CRISIS { UNAFFECTED, BURNOUT, REBELLION }
enum STATUS { STRESS, HEALTH, INEBRIATION, RADICALIZATION, EXTRA_STRESS}
enum STATE { WORKING, PROCEEDING_TO_LOCATION, PROCEEDING_TO_WORK, IDLE }
