extends Node

class_name RatConstants

enum CRISIS_STATE { UNAFFECTED, BURNOUT, REBELLION }
enum STATUS { STRESS, HEALTH, INEBRIATION, RADICALIZATION, EXTRA_STRESS}
enum JOB_STATE { PROCEEDING_TO_WORK, WORKING, PROCEEDING_TO_VICE, VICING, IDLE }
