extends Node

class_name RatConstants

const DEAD_BAND_FLOOR: float = -80.0
const DEAD_BAND_CEILING: float = 80.0

enum CRISIS { UNAFFECTED, BURNOUT, REBELLION }
enum STATUS { STRESS, HEALTH, INEBRIATION, RADICALIZATION, EXTRA_STRESS}
enum STATE { WORKING, PROCEEDING_TO_LOCATION, PROCEEDING_TO_WORK, IDLE }
